# Generated by Django 4.2.16 on 2024-10-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job_type', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('experience_level', models.CharField(max_length=50)),
            ],
        ),
    ]
