# Generated by Django 4.2.16 on 2024-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
